### ISSUE TITLE
Support more audio formats

### ISSUE THREAD

**Issue by HeCorr** [gospacedev/lunar#2]
At the moment only `.mp3` files are supported by lunar, but the audio library being used, [beep](https://github.com/faiface/beep), also supports `.wav`, `.ogg` and `.flac`.

**Comment by HeCorr** [comment]
@gospacedev can you please add the `enhancement` label to this issue?

**Comment by gospacedev** [comment]
Thanks for your response! I created a new function that detects what file type to play.

Now all file types supported by beep are also supported by lunar: 
https://github.com/gospacedev/lunar/blob/master/internal/player.go#L22
