### ISSUE TITLE
Navigate to directories when selecting them

### ISSUE THREAD

**Issue by HeCorr** [gospacedev/lunar#3]
At the moment, lunar crashes when clicking a directory in the list (it also crashes when attempting to play unsupported formats but that's partially fixed on #1).

I believe a basic directory browser should be implemented so that directories can be navigated through and audio files can be played from within them.

**Comment by gospacedev** [comment]
Thanks for bringing this to my attention, I do believe in your idea should be implemented, I've merged your pull request.
