### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by cipherodio** [gospacedev/lunar#4]
Hi sir, i don't have enough knowledge when it comes to golang, i tried installing this on windows 10 machine, but i have an error.

First i download your [binary-v2.2.1](https://github.com/gospacedev/lunar/archive/refs/tags/v2.2.1.zip) then open terminal on that folder.

Then i type the command  `go mod tidy` it download some sort of dependencies, then after that i run the command
`go install github.com\gospacedev\lunar@latest` but it returns an error:

```powershell
go: github.com\gospacedev\lunar@latest: malformed module path "github.com\\gospacedev\\lunar": invalid char '\\'
```

what  went wrong? i really appreciate some help sir. thank you.

Edit:

i manage to install now, but i have few question sir.
1. Is it possible to add multi path directory?  my sample folder structure below:

```
musicfolder
|-------Artistfolder1
|       |--Songnumber1.mp3
|       |--Songnumber2.mp3
|
|-------Artistfolder2
        |--Songnumber3.mp3
        |--Songnumber4.mp3
```

or can i just do `lunar newpath "D:\musicfolder\*"` to add all subfolder inside?

2. Also the when i use down/up arrow to control music volume is not working for me.
Update:

Volume works but very slow, if press down arrow fast up to `Volume 0%` volume is still there, isn't 0% level to have no audio?

**Comment by gospacedev** [comment]
Thanks for bringing this to attention, the issue with lunar not supporting multiple path directories has been noted.  The volume has also been fixed and now becomes silent when set to zero percent.
https://github.com/gospacedev/lunar/commit/a4696905f152994bedfaee25b27d4167ce1ef2db
